
services:
  springboot-app:
    container_name: pigeon-SkyRace
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pigeonSky
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - spring-postgres-network
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - spring-postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pigeonSky

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  spring-postgres-network:
    driver: bridge

volumes:
  postgres-data: